### ISSUE TITLE
Package geonames-index.zip as a resource?

### ISSUE THREAD

**Issue by kwalcock** [clulab/geonorm#1]
Could the files contained in http://clulab.cs.arizona.edu/models/geonames-index.zip possibly be packaged into a jar that can be declared as a project dependency and included in e.g., eidos, at build or assembly time?  At runtime the resources of the jar file would be copied to the cache directory for use by lucene instead of being fetched over a live network connection.  It might also help with versioning.

**Comment by bethard** [comment]
I'd certainly be open to doing that if you can get it to work.

**Comment by kwalcock** [comment]
I'll check on it someday soon.  I'm not sure what the Java API for that would be and need to do some searching.

**Comment by kwalcock** [comment]
Keith started working on this the other day and notes it here to prevent duplication of effort.

**Comment by kwalcock** [comment]
There is an eidos branch, kwalcock-localLucene, which would probably work if some depedency was added to build.sbt that involves a jar file containing the "resource" files from /geonames/index.  This version of the CacheManager extracts the files from this local jar file instead of trying to download a similar zip file from the network and extracting them from there.  This changes the inclusion of the files to build time from run time.  Only the unzipping happens at run time now.  No network connection is needed.  In other words, can the geonames files go to Maven?

**Comment by kwalcock** [comment]
Alternatively, the geonames files could be made a dependency of the geonorm project or even included in that project as resources.

**Comment by kwalcock** [comment]
This still shouldn't have very high priority, but I did run into some comments today about the practice of downloading during execution.  These are from https://2019.splashcon.org/getImage/orig/accpub-OOPSLA2019-licensed.pdf, which isn't the most prestigious article:

```
Downloads during execution. Reviewers spent a long time running
test cases that downloaded data on the fly. Reviewers were also worried
that such data would not always be available.
```

```
Downloads during execution. In
both cases, resources were downloaded
over the internet. One reviewer noted that
the artifact could stop working after a
few years as online resources are deleted.
In one case, resources were downloaded
whenever a reviewer executed a test case.
This made re-executing test cases with
different parameters a time consuming
process, especially exacerbated by a slow
internet connection.
```

**Comment by bethard** [comment]
Finally took a look at https://github.com/clulab/eidos/compare/kwalcock-localLucene. Yes, this looks like the right thing to do; package the index in a .jar and then extract it at runtime if necessary. This extraction code probably needs to be in the geonorm library so that it works even outside of Eidos. Will try to take a look at this after the ACL 2020 submission deadline.

**Comment by bethard** [comment]
Both geonorm and geonames have now been released. You should be able to load the GeoNames index from the classpath if you include the following dependencies:
```
"org.clulab" %  "geonames" % "1.0.0+20200404T005315Z",
"org.clulab" %% "geonorm"  % "1.0.0"
```
And write code like:
```
val tempIndexPath = java.nio.file.Paths.get("temp") // or wherever
val index = org.clulab.geonorm.GeoNamesIndex.fromClasspathJar(tempIndexPath)
```

**Comment by kwalcock** [comment]
This is great!  Are the geonames equivalent to the ones in "http://clulab.cs.arizona.edu/models/geonames+woredas.zip"?

**Comment by bethard** [comment]
No, equivalent to http://clulab.cs.arizona.edu/models/geonames-index.zip. Well, technically a slightly newer GeoNames than that. We should probably re-generate the ones with the woredas tacked on.

@EgoLaparra: I seem to have lost that file. Would you please create a new issue, asking for a geonames+woredas release on artifactory, and attach the GeoNames-formatted woredas file to the issue?

**Comment by kwalcock** [comment]
Thanks.  I don't have a preference, but other people (maybe @BeckySharp) are probably needing to be aware of such details, so I hope they are lurking.

And by the way, it works great!  It is subject of PR https://github.com/clulab/eidos/pull/813.

**Comment by kwalcock** [comment]
It looks like the woredas will remain relevant, so I'm hoping they can be produced for use with the updated version.

**Comment by bethard** [comment]
@kwalcock Yes, it's on the todo list. See issue #8.
