### ISSUE TITLE
Consequences of lucene 7.5.0?

### ISSUE THREAD

**Issue by kwalcock** [clulab/geonorm#10]
Processors is being updated to Stanford CoreNLP 4.4.0 which wants to use Lucene 7.5.0.  This project specifies version 6.6.6.  Do you have any idea what might break in geonorm if we update?

**Comment by bethard** [comment]
Probably most of https://github.com/clulab/geonorm/blob/master/src/main/scala/org/clulab/geonorm/GeoNamesIndex.scala. Lucene makes lots of breaking changes with major version updates.

**Comment by kwalcock** [comment]
See #11 when the time comes.

**Comment by bethard** [comment]
Given that lucine is already on version 9, I imagine we would skip right to that current version.

**Comment by kwalcock** [comment]
That would be nice, but Stanford CoreNLP 4.4.0, the newest, is at Lucene 7.5.0.  That might hold us back.

**Comment by bethard** [comment]
Perhaps there should be an Eidos branch of geonorm that uses whatever older versions are necessary for Eidos.
